/** Textos del chat en el móvil. */
export const chatTexts = {
  title: 'Chat con la tienda',
  subtitle: 'Te contestamos en cuanto podamos.',
  empty: 'Escríbenos y te ayudamos.',
  placeholder: 'Escribe tu mensaje',
  send: 'Enviar',
  typing: 'Escribiendo…',
  storeTyping: 'La tienda está escribiendo',
  tickSending: 'Enviando',
  tickDelivered: 'Recibido',
  tickRead: 'Leído',
  react: 'Reaccionar',
  reply: 'Responder',
  replyingTo: 'Respondiendo a',
  cancelReply: 'Cancelar',
  messageActions: 'Acciones del mensaje',
  reactions: {
    LIKE: 'Me gusta',
    LOVE: 'Me encanta',
    THANKS: 'Gracias',
    SMILE: 'Me hace gracia',
    WOW: 'Me sorprende',
    SAD: 'Lo siento',
  },
  blockedNotice: 'No puedes usar el chat.',
  onlyCustomers: 'El chat es para clientes.',
  verifyFirst: 'Verifica tu correo para poder usar el chat.',
  you: 'Tú',
  store: 'La tienda',
  imageAlt: 'Imagen enviada por la tienda',
  loadError: 'No se pudo abrir el chat',
  sendError: 'No se pudo enviar el mensaje',
  rateLimited: 'Vas muy rápido. Espera un momento antes de seguir.',
  offline: 'Sin conexión con el chat. Reintentando…',
  awayNow: 'Ahora mismo no hay nadie',
  backAt: (date: string) => `Volvemos el ${date}`,
} as const
