/** Textos de la feature auth (solo español). */
export const authTexts = {
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Accede a tu cuenta para comprar y seguir tus pedidos.',
    email: 'Email',
    password: 'Contraseña',
    trustDevice: 'Mantener la sesión en este dispositivo',
    trustDeviceHelp: 'No lo marques en ordenadores compartidos.',
    submit: 'Entrar',
    forgot: '¿Has olvidado tu contraseña?',
    noAccount: '¿No tienes cuenta?',
    register: 'Crear cuenta',
    ended: {
      revoked: 'Tu sesión se ha cerrado por seguridad. Inicia sesión de nuevo.',
      expired: 'Tu sesión ha caducado. Inicia sesión de nuevo.',
      closed: 'Has cerrado esta sesión desde otro dispositivo.',
    },
    welcome: (name: string) => `Hola de nuevo, ${name}`,
  },
  register: {
    title: 'Crear cuenta',
    subtitle: 'Te enviaremos un código para verificar tu email.',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    email: 'Email',
    password: 'Contraseña',
    passwordHelp: 'Mínimo 10 caracteres, con letras y números.',
    confirmPassword: 'Repite la contraseña',
    acceptTerms: 'Acepto los términos y condiciones y la política de privacidad',
    acceptTermsRequired: 'Debes aceptar los términos y la política de privacidad',
    submit: 'Crear cuenta',
    haveAccount: '¿Ya tienes cuenta?',
    login: 'Iniciar sesión',
    codeSent: 'Te hemos enviado un código de verificación',
  },
  verify: {
    title: 'Verifica tu email',
    subtitle: (email: string) => `Introduce el código de 6 dígitos que hemos enviado a ${email}.`,
    code: 'Código de verificación',
    submit: 'Verificar',
    resend: 'Reenviar código',
    resendIn: (s: number) => `Reenviar en ${s} s`,
    resent: 'Si la cuenta está pendiente de verificar, recibirás un código nuevo.',
    success: 'Email verificado. Ya puedes iniciar sesión.',
    missingEmail: 'Falta el email. Vuelve a registrarte o inicia sesión.',
  },
  forgot: {
    title: 'Recuperar contraseña',
    emailStep: 'Introduce tu email y te enviaremos un código.',
    codeStep: (email: string) => `Introduce el código enviado a ${email}.`,
    passwordStep: 'Elige una nueva contraseña.',
    email: 'Email',
    code: 'Código',
    password: 'Nueva contraseña',
    confirmPassword: 'Repite la nueva contraseña',
    sendCode: 'Enviar código',
    verifyCode: 'Continuar',
    save: 'Guardar contraseña',
    success: 'Contraseña actualizada. Inicia sesión con la nueva contraseña.',
    back: 'Volver a iniciar sesión',
  },
  security: {
    title: 'Seguridad',
    changePassword: 'Cambiar contraseña',
    changePasswordHelp: 'Al cambiarla se cerrarán las sesiones en otros dispositivos.',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    confirmPassword: 'Repite la nueva contraseña',
    save: 'Actualizar contraseña',
    passwordChanged: 'Contraseña actualizada.',
    devices: 'Dispositivos',
    devicesHelp: 'Dispositivos con sesión iniciada. Revoca los que no reconozcas.',
    current: 'Este dispositivo',
    trusted: 'De confianza',
    lastSeen: 'Última actividad',
    revoke: 'Revocar',
    revokeTitle: (name: string) => `¿Revocar ${name}?`,
    revokeConfirm: 'Se cerrarán sus sesiones y tendrá que volver a iniciar sesión con contraseña.',
    revoked: (name: string) => `${name} se ha revocado.`,
    revokeOthersTitle: '¿Cerrar las demás sesiones?',
    revokeOthersConfirm: 'Se cerrará la sesión en todos tus dispositivos excepto en este.',
    passwordChangedHelp: 'Se han cerrado las sesiones en otros dispositivos.',
    loadError: 'No se pudieron cargar los dispositivos',
    revokeOthers: 'Cerrar las demás sesiones',
    revokedOthers: (n: number) => (n === 1 ? 'Se ha cerrado 1 sesión.' : `Se han cerrado ${n} sesiones.`),
    noDevices: 'No hay otros dispositivos.',
  },
  twoFactor: {
    title: 'Doble factor',
    help: 'Pide un código de tu app autenticadora además de la contraseña.',
    active: 'Activado',
    inactive: 'Desactivado',
    remainingCodes: (n: number) =>
      n === 1 ? 'Queda 1 código de recuperación' : `Quedan ${n} códigos de recuperación`,
    start: 'Activar doble factor',
    scan: 'Escanea el código con tu app autenticadora, o copia la clave.',
    manualKey: 'Clave manual',
    copyKey: 'Copiar clave',
    copied: 'Copiado al portapapeles',
    codeLabel: 'Código de la app',
    confirm: 'Confirmar y activar',
    cancel: 'Cancelar',
    enabled: 'Doble factor activado',
    recoveryTitle: 'Guarda tus códigos de recuperación',
    recoveryHelp: 'Cada código sirve una sola vez si pierdes el móvil. No volverás a verlos.',
    copyCodes: 'Copiar códigos',
    understood: 'Ya los he guardado',
    disable: 'Desactivar',
    disableTitle: '¿Desactivar el doble factor?',
    disableConfirm: 'Tu cuenta quedará protegida solo con la contraseña.',
    disabled: 'Doble factor desactivado',
    passwordLabel: 'Tu contraseña',
    codeOrRecovery: 'Código de la app o de recuperación',
  },
  loginTwoFactor: {
    title: 'Verificación en dos pasos',
    subtitle: 'Introduce el código de tu app autenticadora.',
    code: 'Código',
    submit: 'Verificar',
    useRecovery: 'Usar un código de recuperación',
    useApp: 'Usar el código de la app',
    recoveryLabel: 'Código de recuperación',
    recoveryHelp: 'Formato XXXX-XXXX. Cada código sirve una sola vez.',
    back: 'Volver',
  },
  menu: {
    account: 'Mi cuenta',
    admin: 'Administración',
    superadmin: 'Configuración',
    logout: 'Cerrar sesión',
    logoutTitle: '¿Cerrar sesión?',
    logoutConfirm: 'Tendrás que volver a iniciar sesión en este dispositivo.',
    loggedOut: 'Has cerrado sesión.',
    login: 'Iniciar sesión',
    userMenu: 'Menú de usuario',
  },
  preferences: {
    title: 'Preferencias',
    haptics: 'Vibración al interactuar',
    intensity: 'Intensidad de la vibración',
    intensityLevels: { subtle: 'Suave', standard: 'Normal', strong: 'Fuerte' },
    testHaptics: 'Probar vibración',
    testHapticsDone: 'Así se siente al añadir al carrito',
    systemHapticsHelp:
      'Si no notas nada, revisa que la vibración del sistema esté activada en los ajustes del teléfono.',
    hapticsHelp: 'Respuesta táctil al pulsar botones, añadir al carrito o confirmar acciones.',
  },
  guard: {
    forbiddenTitle: 'Acceso restringido',
    forbiddenDescription: 'No tienes permisos para ver esta sección.',
  },
} as const
